version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  # streamlit:
  #   container_name: "streamlit"
  #   build: .
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./data:/app/data
  #   depends_on:
  #     - qdrant
